#!/usr/bin/env bash
set -e
export CODECOV_TOKEN="4b6003f8-0dc7-410e-b015-3c6e744c37de"
export RAILS_ENV="test"
export NODE_ENV="test"
export COVERAGE="true"
export DISABLE_SPRING=1
export E2E_COVERAGE="true"
webpack
rails assets:precompile
rails spec
npx nyc merge ./e2e_coverage  coverage.json
npx codecov -f coverage.json -F e2e