export const locOptions = [
    { value: 'ALT', label: 'ALT - Altschul Hall' },
    { value: 'AVH', label: 'AVH - Avery Hall' },
    { value: 'BAR', label: 'BAR - Barnard Hall' },
    { value: 'BLK', label: 'BLK - Black Building' },
    { value: 'BUE', label: 'BUE - Buell Hall' },
    { value: 'BUT', label: 'BUT - Butler Library' },
    { value: 'BWY', label: 'BWY - Broadway Residence Hall' },
    { value: 'CAR', label: 'CAR - Carman Hall' },
    { value: 'CHA', label: 'CHA - Chandler' },
    { value: 'CLA', label: 'CLA - 80 Claremont' },
    { value: 'CSC', label: 'CSC - Computer Science Building' },
    { value: 'DEU', label: 'DEU - Deutsches Haus' },
    { value: 'DIA', label: 'DIA - Diana Center' },
    { value: 'DOD', label: 'DOD - Dodge Building' },
    { value: 'ENG', label: 'ENG - Engineering Terrace' },
    { value: 'FAY', label: 'FAY - Fayerweather' },
    { value: 'FLS', label: 'FLS - Fairchild Life Sciences Building' },
    { value: 'GDH', label: 'GDH - Grace Dodge Hall (TC)' },
    { value: 'GRE', label: 'GRE - Green Hall Law Building' },
    { value: 'HAM', label: 'HAM - Hamilton Hall' },
    { value: 'HAV', label: 'HAV - Havemeyer Hall' },
    { value: 'HEY', label: 'HEY - Heyman Center for Humanities' },
    { value: 'HIS', label: 'HIS - Casa Hispanica' },
    { value: 'HM', label: 'HM - Horace Mann Hall' },
    { value: 'HMB', label: 'HMB - Horace Mann Building' },
    { value: 'HSC', label: 'HSC - Hammer Health Sciences Center' },
    { value: 'HTL', label: 'HTL - Hartley Hall' },
    { value: 'IAB', label: 'IAB - International Affairs Building' },
    { value: 'INTH', label: 'INTH - International House' },
    { value: 'JRN', label: 'JRN - Journalism Building' },
    { value: 'KNT', label: 'KNT - Kent Hall' },
    { value: 'KNX', label: 'KNX - Knox Hall' },
    { value: 'KRAF', label: 'KRAF - Kraft Center' },
    { value: 'LEH', label: 'LEH - Lehman Hall' },
    { value: 'LER', label: 'LER - Alfred Lerner Hall' },
    { value: 'LEW', label: 'LEW - Lewisohn Hall' },
    { value: 'MAT', label: 'MAT - Mathematics Building' },
    { value: 'MCY', label: 'MCY - Macy Hall' },
    { value: 'MIL', label: 'MIL - Milbank Hall, Barnard' },
    { value: 'MLC', label: 'MLC - Milstein Center, Barnard' },
    { value: 'MUD', label: 'MUD - Seeley W. Mudd Building' },
    { value: 'NASH', label: 'NASH - Nash Building' },
    { value: 'NWC', label: 'NWC - Northwest Corner' },
    { value: 'PHI', label: 'PHI - Philosophy Hall' },
    { value: 'PRN', label: 'PRN - Prentis Hall' },
    { value: 'PUP', label: 'PUP - Pupin Laboratories' },
    { value: 'RSC', label: 'RSC - Riverside Church' },
    { value: 'SCEP', label: 'SCEP - Schapiro Center for Engineering & Physical Science Research' },
    { value: 'SCH', label: 'SCH - Schermerhorn Hall' },
    { value: 'SCHP', label: 'SCHP - Schapiro (Residence Hall)' },
    { value: 'SSW', label: 'SSW - School of Social Work' },
    { value: 'TH/THM', label: 'TH/THM - Thompson Hall (TC)' },
    { value: 'URI', label: 'URI - Uris Hall' },
    { value: 'UTS', label: 'UTS - Union Theological Seminary' },
    { value: 'WAT', label: 'WAT - Watson Hall' },
    { value: 'WJW', label: 'WJW - W & J Warren (Law & Business)' },
    { value: 'ZB', label: 'ZB - Zankel' },
    { value: 'Other', label: 'Other'}
  ];